### ISSUE TITLE
Package not installable

### ISSUE THREAD

**Issue by PhilippFinke88** [neobotix/neo_mp_400#7]
The package isn't exporting its files to the install folder when building with "catkin_make install". I prepared a fixed CMakeLists.txt but I'm not able to perform a pull request as I'm not allowed to push branches. This problem persists in other packages too.
[CMakeLists.txt](https://github.com/neobotix/neo_mp_400/files/5971596/CMakeLists.txt)

**Comment by padhupradheep** [comment]
Sorry for taking long to respond to you. But, currently we want our package to stay in the devel space rather than installing it!
